// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: forum.proto

package server

import (
	"context"

	"forum/internal/logic/forum"
	"forum/internal/svc"
	"forum/types/forum"
)

type ForumServer struct {
	svcCtx *svc.ServiceContext
	forum.UnimplementedForumServer
}

func NewForumServer(svcCtx *svc.ServiceContext) *ForumServer {
	return &ForumServer{
		svcCtx: svcCtx,
	}
}

// 创建内容（parent_id=0 为帖子，>0 为评论/回复）
func (s *ForumServer) CreatePost(ctx context.Context, in *forum.CreatePostRequest) (*forum.CreatePostResponse, error) {
	l := forumlogic.NewCreatePostLogic(ctx, s.svcCtx)
	return l.CreatePost(in)
}

// 更新内容（删除）
func (s *ForumServer) UpdatePost(ctx context.Context, in *forum.UpdatePostRequest) (*forum.UpdatePostResponse, error) {
	l := forumlogic.NewUpdatePostLogic(ctx, s.svcCtx)
	return l.UpdatePost(in)
}

// 获取内容
func (s *ForumServer) GetPost(ctx context.Context, in *forum.GetPostRequest) (*forum.GetPostResponse, error) {
	l := forumlogic.NewGetPostLogic(ctx, s.svcCtx)
	return l.GetPost(in)
}

// 获取内容列表（按 parent_id 区分帖子/评论）
func (s *ForumServer) ListPost(ctx context.Context, in *forum.ListPostRequest) (*forum.ListPostResponse, error) {
	l := forumlogic.NewListPostLogic(ctx, s.svcCtx)
	return l.ListPost(in)
}

// 收藏
func (s *ForumServer) Fav(ctx context.Context, in *forum.FavRequest) (*forum.FavResponse, error) {
	l := forumlogic.NewFavLogic(ctx, s.svcCtx)
	return l.Fav(in)
}

// 获取收藏列表
func (s *ForumServer) ListFav(ctx context.Context, in *forum.ListFavRequest) (*forum.ListFavResponse, error) {
	l := forumlogic.NewListFavLogic(ctx, s.svcCtx)
	return l.ListFav(in)
}

// 点赞
func (s *ForumServer) Like(ctx context.Context, in *forum.LikeRequest) (*forum.LikeResponse, error) {
	l := forumlogic.NewLikeLogic(ctx, s.svcCtx)
	return l.Like(in)
}

// 获取点赞列表
func (s *ForumServer) ListLike(ctx context.Context, in *forum.ListLikeRequest) (*forum.ListLikeResponse, error) {
	l := forumlogic.NewListLikeLogic(ctx, s.svcCtx)
	return l.ListLike(in)
}
