// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: forum.proto

package forum

import (
	"context"

	"forum/types/forum"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CreatePostRequest  = forum.CreatePostRequest
	CreatePostResponse = forum.CreatePostResponse
	FavRequest         = forum.FavRequest
	FavResponse        = forum.FavResponse
	GetPostRequest     = forum.GetPostRequest
	GetPostResponse    = forum.GetPostResponse
	LikeRequest        = forum.LikeRequest
	LikeResponse       = forum.LikeResponse
	ListFavRequest     = forum.ListFavRequest
	ListFavResponse    = forum.ListFavResponse
	ListLikeRequest    = forum.ListLikeRequest
	ListLikeResponse   = forum.ListLikeResponse
	ListPostRequest    = forum.ListPostRequest
	ListPostResponse   = forum.ListPostResponse
	UpdatePostRequest  = forum.UpdatePostRequest
	UpdatePostResponse = forum.UpdatePostResponse

	Forum interface {
		// 创建内容（parent_id=0 为帖子，>0 为评论/回复）
		CreatePost(ctx context.Context, in *CreatePostRequest, opts ...grpc.CallOption) (*CreatePostResponse, error)
		// 更新内容（删除）
		UpdatePost(ctx context.Context, in *UpdatePostRequest, opts ...grpc.CallOption) (*UpdatePostResponse, error)
		// 获取内容
		GetPost(ctx context.Context, in *GetPostRequest, opts ...grpc.CallOption) (*GetPostResponse, error)
		// 获取内容列表（按 parent_id 区分帖子/评论）
		ListPost(ctx context.Context, in *ListPostRequest, opts ...grpc.CallOption) (*ListPostResponse, error)
		// 收藏
		Fav(ctx context.Context, in *FavRequest, opts ...grpc.CallOption) (*FavResponse, error)
		// 获取收藏列表
		ListFav(ctx context.Context, in *ListFavRequest, opts ...grpc.CallOption) (*ListFavResponse, error)
		// 点赞
		Like(ctx context.Context, in *LikeRequest, opts ...grpc.CallOption) (*LikeResponse, error)
		// 获取点赞列表
		ListLike(ctx context.Context, in *ListLikeRequest, opts ...grpc.CallOption) (*ListLikeResponse, error)
	}

	defaultForum struct {
		cli zrpc.Client
	}
)

func NewForum(cli zrpc.Client) Forum {
	return &defaultForum{
		cli: cli,
	}
}

// 创建内容（parent_id=0 为帖子，>0 为评论/回复）
func (m *defaultForum) CreatePost(ctx context.Context, in *CreatePostRequest, opts ...grpc.CallOption) (*CreatePostResponse, error) {
	client := forum.NewForumClient(m.cli.Conn())
	return client.CreatePost(ctx, in, opts...)
}

// 更新内容（删除）
func (m *defaultForum) UpdatePost(ctx context.Context, in *UpdatePostRequest, opts ...grpc.CallOption) (*UpdatePostResponse, error) {
	client := forum.NewForumClient(m.cli.Conn())
	return client.UpdatePost(ctx, in, opts...)
}

// 获取内容
func (m *defaultForum) GetPost(ctx context.Context, in *GetPostRequest, opts ...grpc.CallOption) (*GetPostResponse, error) {
	client := forum.NewForumClient(m.cli.Conn())
	return client.GetPost(ctx, in, opts...)
}

// 获取内容列表（按 parent_id 区分帖子/评论）
func (m *defaultForum) ListPost(ctx context.Context, in *ListPostRequest, opts ...grpc.CallOption) (*ListPostResponse, error) {
	client := forum.NewForumClient(m.cli.Conn())
	return client.ListPost(ctx, in, opts...)
}

// 收藏
func (m *defaultForum) Fav(ctx context.Context, in *FavRequest, opts ...grpc.CallOption) (*FavResponse, error) {
	client := forum.NewForumClient(m.cli.Conn())
	return client.Fav(ctx, in, opts...)
}

// 获取收藏列表
func (m *defaultForum) ListFav(ctx context.Context, in *ListFavRequest, opts ...grpc.CallOption) (*ListFavResponse, error) {
	client := forum.NewForumClient(m.cli.Conn())
	return client.ListFav(ctx, in, opts...)
}

// 点赞
func (m *defaultForum) Like(ctx context.Context, in *LikeRequest, opts ...grpc.CallOption) (*LikeResponse, error) {
	client := forum.NewForumClient(m.cli.Conn())
	return client.Like(ctx, in, opts...)
}

// 获取点赞列表
func (m *defaultForum) ListLike(ctx context.Context, in *ListLikeRequest, opts ...grpc.CallOption) (*ListLikeResponse, error) {
	client := forum.NewForumClient(m.cli.Conn())
	return client.ListLike(ctx, in, opts...)
}
