// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.4
// source: forum.proto

package forum

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_STATUS_UNKNOWN   Status = 0
	Status_STATUS_PUBLISHED Status = 30 // 已发布
	Status_STATUS_DELETED   Status = 90 // 已删除
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0:  "STATUS_UNKNOWN",
		30: "STATUS_PUBLISHED",
		90: "STATUS_DELETED",
	}
	Status_value = map[string]int32{
		"STATUS_UNKNOWN":   0,
		"STATUS_PUBLISHED": 30,
		"STATUS_DELETED":   90,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_forum_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_forum_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_forum_proto_rawDescGZIP(), []int{0}
}

type BaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseResponse) Reset() {
	*x = BaseResponse{}
	mi := &file_forum_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseResponse) ProtoMessage() {}

func (x *BaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_forum_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseResponse.ProtoReflect.Descriptor instead.
func (*BaseResponse) Descriptor() ([]byte, []int) {
	return file_forum_proto_rawDescGZIP(), []int{0}
}

func (x *BaseResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *BaseResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Pagination struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int64                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`                         // 当前页
	PageSize      int64                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"` // 每页大小
	Total         int64                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`                       // 总数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pagination) Reset() {
	*x = Pagination{}
	mi := &file_forum_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pagination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pagination) ProtoMessage() {}

func (x *Pagination) ProtoReflect() protoreflect.Message {
	mi := &file_forum_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pagination.ProtoReflect.Descriptor instead.
func (*Pagination) Descriptor() ([]byte, []int) {
	return file_forum_proto_rawDescGZIP(), []int{1}
}

func (x *Pagination) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *Pagination) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *Pagination) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type Sort struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"` // 排序字段
	Order         string                 `protobuf:"bytes,2,opt,name=order,proto3" json:"order,omitempty"` // 排序方式 asc/desc
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sort) Reset() {
	*x = Sort{}
	mi := &file_forum_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sort) ProtoMessage() {}

func (x *Sort) ProtoReflect() protoreflect.Message {
	mi := &file_forum_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sort.ProtoReflect.Descriptor instead.
func (*Sort) Descriptor() ([]byte, []int) {
	return file_forum_proto_rawDescGZIP(), []int{2}
}

func (x *Sort) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *Sort) GetOrder() string {
	if x != nil {
		return x.Order
	}
	return ""
}

// 帖子 (内容统一模型，纯 parent_id 邻接树，最多 2 层)
//   - parent_id = 0          : 帖子(根节点)
//   - parent_id = 帖子id     : 一级评论
//   - parent_id = 一级评论id : 回复
type Post struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                          // 主键
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                    // 用户ID
	Account       string                 `protobuf:"bytes,3,opt,name=account,proto3" json:"account,omitempty"`                                 // 用户账号名
	Status        Status                 `protobuf:"varint,4,opt,name=status,proto3,enum=forum.Status" json:"status,omitempty"`                // 状态 30:已发布 90:已删除
	Remark        string                 `protobuf:"bytes,5,opt,name=remark,proto3" json:"remark,omitempty"`                                   // 备注
	Content       string                 `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`                                 // 内容
	Images        []string               `protobuf:"bytes,7,rep,name=images,proto3" json:"images,omitempty"`                                   // 图片信息
	WordCount     int32                  `protobuf:"varint,8,opt,name=word_count,json=wordCount,proto3" json:"word_count,omitempty"`           // 字数
	ViewCount     int32                  `protobuf:"varint,9,opt,name=view_count,json=viewCount,proto3" json:"view_count,omitempty"`           // 浏览量
	LikeCount     int32                  `protobuf:"varint,10,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"`          // 点赞量
	CommentCount  int32                  `protobuf:"varint,11,opt,name=comment_count,json=commentCount,proto3" json:"comment_count,omitempty"` // 评论量
	FavCount      int32                  `protobuf:"varint,12,opt,name=fav_count,json=favCount,proto3" json:"fav_count,omitempty"`             // 收藏量
	PublishTime   int64                  `protobuf:"varint,13,opt,name=publish_time,json=publishTime,proto3" json:"publish_time,omitempty"`    // 发布时间
	IsLiked       bool                   `protobuf:"varint,14,opt,name=is_liked,json=isLiked,proto3" json:"is_liked,omitempty"`                // 当前操作人是否已点赞
	IsFav         bool                   `protobuf:"varint,15,opt,name=is_fav,json=isFav,proto3" json:"is_fav,omitempty"`                      // 当前操作人是否已收藏
	ParentId      int64                  `protobuf:"varint,16,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`             // 父节点ID 0:帖子 帖子id:一级评论 评论id:回复
	IpAddress     string                 `protobuf:"bytes,18,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`           // IP地址
	Parent        *Post                  `protobuf:"bytes,20,opt,name=parent,proto3" json:"parent,omitempty"`                                  // 直接父节点(评论场景下由服务端回填; 回复的根帖子为 parent.parent)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Post) Reset() {
	*x = Post{}
	mi := &file_forum_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Post) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Post) ProtoMessage() {}

func (x *Post) ProtoReflect() protoreflect.Message {
	mi := &file_forum_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Post.ProtoReflect.Descriptor instead.
func (*Post) Descriptor() ([]byte, []int) {
	return file_forum_proto_rawDescGZIP(), []int{3}
}

func (x *Post) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Post) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Post) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *Post) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNKNOWN
}

func (x *Post) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *Post) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Post) GetImages() []string {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *Post) GetWordCount() int32 {
	if x != nil {
		return x.WordCount
	}
	return 0
}

func (x *Post) GetViewCount() int32 {
	if x != nil {
		return x.ViewCount
	}
	return 0
}

func (x *Post) GetLikeCount() int32 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

func (x *Post) GetCommentCount() int32 {
	if x != nil {
		return x.CommentCount
	}
	return 0
}

func (x *Post) GetFavCount() int32 {
	if x != nil {
		return x.FavCount
	}
	return 0
}

func (x *Post) GetPublishTime() int64 {
	if x != nil {
		return x.PublishTime
	}
	return 0
}

func (x *Post) GetIsLiked() bool {
	if x != nil {
		return x.IsLiked
	}
	return false
}

func (x *Post) GetIsFav() bool {
	if x != nil {
		return x.IsFav
	}
	return false
}

func (x *Post) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *Post) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *Post) GetParent() *Post {
	if x != nil {
		return x.Parent
	}
	return nil
}

// 点赞
type Like struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                   // 主键
	TargetId      int64                  `protobuf:"varint,2,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`       // 目标内容ID (帖子或评论)
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`             // 用户ID
	Account       string                 `protobuf:"bytes,4,opt,name=account,proto3" json:"account,omitempty"`                          // 用户账号名
	Status        Status                 `protobuf:"varint,5,opt,name=status,proto3,enum=forum.Status" json:"status,omitempty"`         // 状态 30:正常 90:已删除
	IpAddress     string                 `protobuf:"bytes,6,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`     // IP地址
	CreateTime    int64                  `protobuf:"varint,8,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"` // 创建时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Like) Reset() {
	*x = Like{}
	mi := &file_forum_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Like) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Like) ProtoMessage() {}

func (x *Like) ProtoReflect() protoreflect.Message {
	mi := &file_forum_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Like.ProtoReflect.Descriptor instead.
func (*Like) Descriptor() ([]byte, []int) {
	return file_forum_proto_rawDescGZIP(), []int{4}
}

func (x *Like) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Like) GetTargetId() int64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *Like) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Like) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *Like) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNKNOWN
}

func (x *Like) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *Like) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

// 收藏
type Fav struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                   // 主键
	TargetId      int64                  `protobuf:"varint,2,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`       // 目标内容ID (帖子或评论)
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`             // 用户ID
	Account       string                 `protobuf:"bytes,4,opt,name=account,proto3" json:"account,omitempty"`                          // 用户账号名
	Status        Status                 `protobuf:"varint,5,opt,name=status,proto3,enum=forum.Status" json:"status,omitempty"`         // 状态 30:正常 90:已删除
	CreateTime    int64                  `protobuf:"varint,6,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"` // 创建时间
	Post          *Post                  `protobuf:"bytes,7,opt,name=post,proto3" json:"post,omitempty"`                                // 目标内容 (帖子或评论, 统一用 Post 表示)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Fav) Reset() {
	*x = Fav{}
	mi := &file_forum_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Fav) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Fav) ProtoMessage() {}

func (x *Fav) ProtoReflect() protoreflect.Message {
	mi := &file_forum_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Fav.ProtoReflect.Descriptor instead.
func (*Fav) Descriptor() ([]byte, []int) {
	return file_forum_proto_rawDescGZIP(), []int{5}
}

func (x *Fav) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Fav) GetTargetId() int64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *Fav) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Fav) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *Fav) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNKNOWN
}

func (x *Fav) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *Fav) GetPost() *Post {
	if x != nil {
		return x.Post
	}
	return nil
}

type CreatePostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Post          *Post                  `protobuf:"bytes,1,opt,name=post,proto3" json:"post,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePostRequest) Reset() {
	*x = CreatePostRequest{}
	mi := &file_forum_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePostRequest) ProtoMessage() {}

func (x *CreatePostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_forum_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePostRequest.ProtoReflect.Descriptor instead.
func (*CreatePostRequest) Descriptor() ([]byte, []int) {
	return file_forum_proto_rawDescGZIP(), []int{6}
}

func (x *CreatePostRequest) GetPost() *Post {
	if x != nil {
		return x.Post
	}
	return nil
}

type CreatePostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BaseResp      *BaseResponse          `protobuf:"bytes,1,opt,name=base_resp,json=baseResp,proto3" json:"base_resp,omitempty"`
	Post          *Post                  `protobuf:"bytes,2,opt,name=post,proto3" json:"post,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePostResponse) Reset() {
	*x = CreatePostResponse{}
	mi := &file_forum_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePostResponse) ProtoMessage() {}

func (x *CreatePostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_forum_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePostResponse.ProtoReflect.Descriptor instead.
func (*CreatePostResponse) Descriptor() ([]byte, []int) {
	return file_forum_proto_rawDescGZIP(), []int{7}
}

func (x *CreatePostResponse) GetBaseResp() *BaseResponse {
	if x != nil {
		return x.BaseResp
	}
	return nil
}

func (x *CreatePostResponse) GetPost() *Post {
	if x != nil {
		return x.Post
	}
	return nil
}

type UpdatePostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Post          *Post                  `protobuf:"bytes,1,opt,name=post,proto3" json:"post,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePostRequest) Reset() {
	*x = UpdatePostRequest{}
	mi := &file_forum_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePostRequest) ProtoMessage() {}

func (x *UpdatePostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_forum_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePostRequest.ProtoReflect.Descriptor instead.
func (*UpdatePostRequest) Descriptor() ([]byte, []int) {
	return file_forum_proto_rawDescGZIP(), []int{8}
}

func (x *UpdatePostRequest) GetPost() *Post {
	if x != nil {
		return x.Post
	}
	return nil
}

type UpdatePostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BaseResp      *BaseResponse          `protobuf:"bytes,1,opt,name=base_resp,json=baseResp,proto3" json:"base_resp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePostResponse) Reset() {
	*x = UpdatePostResponse{}
	mi := &file_forum_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePostResponse) ProtoMessage() {}

func (x *UpdatePostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_forum_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePostResponse.ProtoReflect.Descriptor instead.
func (*UpdatePostResponse) Descriptor() ([]byte, []int) {
	return file_forum_proto_rawDescGZIP(), []int{9}
}

func (x *UpdatePostResponse) GetBaseResp() *BaseResponse {
	if x != nil {
		return x.BaseResp
	}
	return nil
}

type GetPostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPostRequest) Reset() {
	*x = GetPostRequest{}
	mi := &file_forum_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostRequest) ProtoMessage() {}

func (x *GetPostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_forum_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostRequest.ProtoReflect.Descriptor instead.
func (*GetPostRequest) Descriptor() ([]byte, []int) {
	return file_forum_proto_rawDescGZIP(), []int{10}
}

func (x *GetPostRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetPostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BaseResp      *BaseResponse          `protobuf:"bytes,1,opt,name=base_resp,json=baseResp,proto3" json:"base_resp,omitempty"`
	Post          *Post                  `protobuf:"bytes,2,opt,name=post,proto3" json:"post,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPostResponse) Reset() {
	*x = GetPostResponse{}
	mi := &file_forum_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostResponse) ProtoMessage() {}

func (x *GetPostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_forum_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostResponse.ProtoReflect.Descriptor instead.
func (*GetPostResponse) Descriptor() ([]byte, []int) {
	return file_forum_proto_rawDescGZIP(), []int{11}
}

func (x *GetPostResponse) GetBaseResp() *BaseResponse {
	if x != nil {
		return x.BaseResp
	}
	return nil
}

func (x *GetPostResponse) GetPost() *Post {
	if x != nil {
		return x.Post
	}
	return nil
}

type PostFilter struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PostId           int64                  `protobuf:"varint,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`                                 // 帖子ID (可选，用于查询指定帖子)
	Content          string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`                                              // 内容模糊搜索 (可选, 仅对帖子有效)
	Status           []Status               `protobuf:"varint,3,rep,packed,name=status,proto3,enum=forum.Status" json:"status,omitempty"`                      // 状态筛选 (可选, 默认仅已发布)
	Account          string                 `protobuf:"bytes,4,opt,name=account,proto3" json:"account,omitempty"`                                              // 用户账号名 (可选)
	PublishTimeStart int64                  `protobuf:"varint,5,opt,name=publish_time_start,json=publishTimeStart,proto3" json:"publish_time_start,omitempty"` // 发布时间开始时间 (可选)
	PublishTimeEnd   int64                  `protobuf:"varint,6,opt,name=publish_time_end,json=publishTimeEnd,proto3" json:"publish_time_end,omitempty"`       // 发布时间结束时间 (可选)
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PostFilter) Reset() {
	*x = PostFilter{}
	mi := &file_forum_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostFilter) ProtoMessage() {}

func (x *PostFilter) ProtoReflect() protoreflect.Message {
	mi := &file_forum_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostFilter.ProtoReflect.Descriptor instead.
func (*PostFilter) Descriptor() ([]byte, []int) {
	return file_forum_proto_rawDescGZIP(), []int{12}
}

func (x *PostFilter) GetPostId() int64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *PostFilter) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *PostFilter) GetStatus() []Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *PostFilter) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *PostFilter) GetPublishTimeStart() int64 {
	if x != nil {
		return x.PublishTimeStart
	}
	return 0
}

func (x *PostFilter) GetPublishTimeEnd() int64 {
	if x != nil {
		return x.PublishTimeEnd
	}
	return 0
}

type ListPostRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Pagination *Pagination            `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	PostFilter *PostFilter            `protobuf:"bytes,2,opt,name=post_filter,json=postFilter,proto3" json:"post_filter,omitempty"`  // 帖子筛选条件
	Sorts      []*Sort                `protobuf:"bytes,3,rep,name=sorts,proto3" json:"sorts,omitempty"`                              // 排序条件
	OperatorId int64                  `protobuf:"varint,4,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"` // 操作人ID
	UserId     int64                  `protobuf:"varint,5,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`             // 用户ID (可选，按作者过滤)
	// 父节点过滤: 0=帖子(根); >0=该节点的直接子节点(评论/回复); -1=仅评论(parent_id<>0)
	ParentId      int64 `protobuf:"varint,6,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPostRequest) Reset() {
	*x = ListPostRequest{}
	mi := &file_forum_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPostRequest) ProtoMessage() {}

func (x *ListPostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_forum_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPostRequest.ProtoReflect.Descriptor instead.
func (*ListPostRequest) Descriptor() ([]byte, []int) {
	return file_forum_proto_rawDescGZIP(), []int{13}
}

func (x *ListPostRequest) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListPostRequest) GetPostFilter() *PostFilter {
	if x != nil {
		return x.PostFilter
	}
	return nil
}

func (x *ListPostRequest) GetSorts() []*Sort {
	if x != nil {
		return x.Sorts
	}
	return nil
}

func (x *ListPostRequest) GetOperatorId() int64 {
	if x != nil {
		return x.OperatorId
	}
	return 0
}

func (x *ListPostRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListPostRequest) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

type ListPostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BaseResp      *BaseResponse          `protobuf:"bytes,1,opt,name=base_resp,json=baseResp,proto3" json:"base_resp,omitempty"`
	Pagination    *Pagination            `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Posts         []*Post                `protobuf:"bytes,3,rep,name=posts,proto3" json:"posts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPostResponse) Reset() {
	*x = ListPostResponse{}
	mi := &file_forum_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPostResponse) ProtoMessage() {}

func (x *ListPostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_forum_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPostResponse.ProtoReflect.Descriptor instead.
func (*ListPostResponse) Descriptor() ([]byte, []int) {
	return file_forum_proto_rawDescGZIP(), []int{14}
}

func (x *ListPostResponse) GetBaseResp() *BaseResponse {
	if x != nil {
		return x.BaseResp
	}
	return nil
}

func (x *ListPostResponse) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListPostResponse) GetPosts() []*Post {
	if x != nil {
		return x.Posts
	}
	return nil
}

type FavRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`       // 用户ID
	TargetId      int64                  `protobuf:"varint,2,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"` // 目标内容ID (帖子或评论)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FavRequest) Reset() {
	*x = FavRequest{}
	mi := &file_forum_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FavRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FavRequest) ProtoMessage() {}

func (x *FavRequest) ProtoReflect() protoreflect.Message {
	mi := &file_forum_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FavRequest.ProtoReflect.Descriptor instead.
func (*FavRequest) Descriptor() ([]byte, []int) {
	return file_forum_proto_rawDescGZIP(), []int{15}
}

func (x *FavRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *FavRequest) GetTargetId() int64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

type FavResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BaseResp      *BaseResponse          `protobuf:"bytes,1,opt,name=base_resp,json=baseResp,proto3" json:"base_resp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FavResponse) Reset() {
	*x = FavResponse{}
	mi := &file_forum_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FavResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FavResponse) ProtoMessage() {}

func (x *FavResponse) ProtoReflect() protoreflect.Message {
	mi := &file_forum_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FavResponse.ProtoReflect.Descriptor instead.
func (*FavResponse) Descriptor() ([]byte, []int) {
	return file_forum_proto_rawDescGZIP(), []int{16}
}

func (x *FavResponse) GetBaseResp() *BaseResponse {
	if x != nil {
		return x.BaseResp
	}
	return nil
}

type ListFavRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pagination    *Pagination            `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                 // 用户ID
	Sorts         []*Sort                `protobuf:"bytes,3,rep,name=sorts,proto3" json:"sorts,omitempty"`                                  // 排序条件
	TargetIds     []int64                `protobuf:"varint,4,rep,packed,name=target_ids,json=targetIds,proto3" json:"target_ids,omitempty"` // 目标内容ID列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFavRequest) Reset() {
	*x = ListFavRequest{}
	mi := &file_forum_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFavRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFavRequest) ProtoMessage() {}

func (x *ListFavRequest) ProtoReflect() protoreflect.Message {
	mi := &file_forum_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFavRequest.ProtoReflect.Descriptor instead.
func (*ListFavRequest) Descriptor() ([]byte, []int) {
	return file_forum_proto_rawDescGZIP(), []int{17}
}

func (x *ListFavRequest) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListFavRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListFavRequest) GetSorts() []*Sort {
	if x != nil {
		return x.Sorts
	}
	return nil
}

func (x *ListFavRequest) GetTargetIds() []int64 {
	if x != nil {
		return x.TargetIds
	}
	return nil
}

type ListFavResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BaseResp      *BaseResponse          `protobuf:"bytes,1,opt,name=base_resp,json=baseResp,proto3" json:"base_resp,omitempty"`
	Pagination    *Pagination            `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Favs          []*Fav                 `protobuf:"bytes,3,rep,name=favs,proto3" json:"favs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFavResponse) Reset() {
	*x = ListFavResponse{}
	mi := &file_forum_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFavResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFavResponse) ProtoMessage() {}

func (x *ListFavResponse) ProtoReflect() protoreflect.Message {
	mi := &file_forum_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFavResponse.ProtoReflect.Descriptor instead.
func (*ListFavResponse) Descriptor() ([]byte, []int) {
	return file_forum_proto_rawDescGZIP(), []int{18}
}

func (x *ListFavResponse) GetBaseResp() *BaseResponse {
	if x != nil {
		return x.BaseResp
	}
	return nil
}

func (x *ListFavResponse) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListFavResponse) GetFavs() []*Fav {
	if x != nil {
		return x.Favs
	}
	return nil
}

type LikeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`         // 用户ID
	TargetId      int64                  `protobuf:"varint,2,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`   // 目标内容ID (帖子或评论)
	IpAddress     string                 `protobuf:"bytes,3,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"` // IP地址
	Device        int32                  `protobuf:"varint,4,opt,name=device,proto3" json:"device,omitempty"`                       // 设备 和Users服务的Platform类型一致
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeRequest) Reset() {
	*x = LikeRequest{}
	mi := &file_forum_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeRequest) ProtoMessage() {}

func (x *LikeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_forum_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeRequest.ProtoReflect.Descriptor instead.
func (*LikeRequest) Descriptor() ([]byte, []int) {
	return file_forum_proto_rawDescGZIP(), []int{19}
}

func (x *LikeRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *LikeRequest) GetTargetId() int64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *LikeRequest) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *LikeRequest) GetDevice() int32 {
	if x != nil {
		return x.Device
	}
	return 0
}

type LikeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BaseResp      *BaseResponse          `protobuf:"bytes,1,opt,name=base_resp,json=baseResp,proto3" json:"base_resp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeResponse) Reset() {
	*x = LikeResponse{}
	mi := &file_forum_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeResponse) ProtoMessage() {}

func (x *LikeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_forum_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeResponse.ProtoReflect.Descriptor instead.
func (*LikeResponse) Descriptor() ([]byte, []int) {
	return file_forum_proto_rawDescGZIP(), []int{20}
}

func (x *LikeResponse) GetBaseResp() *BaseResponse {
	if x != nil {
		return x.BaseResp
	}
	return nil
}

type ListLikeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pagination    *Pagination            `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                 // 用户ID
	Sorts         []*Sort                `protobuf:"bytes,3,rep,name=sorts,proto3" json:"sorts,omitempty"`                                  // 排序条件
	TargetIds     []int64                `protobuf:"varint,4,rep,packed,name=target_ids,json=targetIds,proto3" json:"target_ids,omitempty"` // 目标内容ID列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLikeRequest) Reset() {
	*x = ListLikeRequest{}
	mi := &file_forum_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLikeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLikeRequest) ProtoMessage() {}

func (x *ListLikeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_forum_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLikeRequest.ProtoReflect.Descriptor instead.
func (*ListLikeRequest) Descriptor() ([]byte, []int) {
	return file_forum_proto_rawDescGZIP(), []int{21}
}

func (x *ListLikeRequest) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListLikeRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListLikeRequest) GetSorts() []*Sort {
	if x != nil {
		return x.Sorts
	}
	return nil
}

func (x *ListLikeRequest) GetTargetIds() []int64 {
	if x != nil {
		return x.TargetIds
	}
	return nil
}

type ListLikeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BaseResp      *BaseResponse          `protobuf:"bytes,1,opt,name=base_resp,json=baseResp,proto3" json:"base_resp,omitempty"`
	Pagination    *Pagination            `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Likes         []*Like                `protobuf:"bytes,3,rep,name=likes,proto3" json:"likes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLikeResponse) Reset() {
	*x = ListLikeResponse{}
	mi := &file_forum_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLikeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLikeResponse) ProtoMessage() {}

func (x *ListLikeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_forum_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLikeResponse.ProtoReflect.Descriptor instead.
func (*ListLikeResponse) Descriptor() ([]byte, []int) {
	return file_forum_proto_rawDescGZIP(), []int{22}
}

func (x *ListLikeResponse) GetBaseResp() *BaseResponse {
	if x != nil {
		return x.BaseResp
	}
	return nil
}

func (x *ListLikeResponse) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListLikeResponse) GetLikes() []*Like {
	if x != nil {
		return x.Likes
	}
	return nil
}

var File_forum_proto protoreflect.FileDescriptor

const file_forum_proto_rawDesc = "" +
	"\n" +
	"\vforum.proto\x12\x05forum\"<\n" +
	"\fBaseResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"S\n" +
	"\n" +
	"Pagination\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x03R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x03R\bpageSize\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x03R\x05total\"2\n" +
	"\x04Sort\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12\x14\n" +
	"\x05order\x18\x02 \x01(\tR\x05order\"\x8f\x04\n" +
	"\x04Post\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x18\n" +
	"\aaccount\x18\x03 \x01(\tR\aaccount\x12%\n" +
	"\x06status\x18\x04 \x01(\x0e2\r.forum.StatusR\x06status\x12\x16\n" +
	"\x06remark\x18\x05 \x01(\tR\x06remark\x12\x18\n" +
	"\acontent\x18\x06 \x01(\tR\acontent\x12\x16\n" +
	"\x06images\x18\a \x03(\tR\x06images\x12\x1d\n" +
	"\n" +
	"word_count\x18\b \x01(\x05R\twordCount\x12\x1d\n" +
	"\n" +
	"view_count\x18\t \x01(\x05R\tviewCount\x12\x1d\n" +
	"\n" +
	"like_count\x18\n" +
	" \x01(\x05R\tlikeCount\x12#\n" +
	"\rcomment_count\x18\v \x01(\x05R\fcommentCount\x12\x1b\n" +
	"\tfav_count\x18\f \x01(\x05R\bfavCount\x12!\n" +
	"\fpublish_time\x18\r \x01(\x03R\vpublishTime\x12\x19\n" +
	"\bis_liked\x18\x0e \x01(\bR\aisLiked\x12\x15\n" +
	"\x06is_fav\x18\x0f \x01(\bR\x05isFav\x12\x1b\n" +
	"\tparent_id\x18\x10 \x01(\x03R\bparentId\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x12 \x01(\tR\tipAddress\x12#\n" +
	"\x06parent\x18\x14 \x01(\v2\v.forum.PostR\x06parent\"\xcd\x01\n" +
	"\x04Like\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\ttarget_id\x18\x02 \x01(\x03R\btargetId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12\x18\n" +
	"\aaccount\x18\x04 \x01(\tR\aaccount\x12%\n" +
	"\x06status\x18\x05 \x01(\x0e2\r.forum.StatusR\x06status\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x06 \x01(\tR\tipAddress\x12\x1f\n" +
	"\vcreate_time\x18\b \x01(\x03R\n" +
	"createTime\"\xce\x01\n" +
	"\x03Fav\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\ttarget_id\x18\x02 \x01(\x03R\btargetId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12\x18\n" +
	"\aaccount\x18\x04 \x01(\tR\aaccount\x12%\n" +
	"\x06status\x18\x05 \x01(\x0e2\r.forum.StatusR\x06status\x12\x1f\n" +
	"\vcreate_time\x18\x06 \x01(\x03R\n" +
	"createTime\x12\x1f\n" +
	"\x04post\x18\a \x01(\v2\v.forum.PostR\x04post\"4\n" +
	"\x11CreatePostRequest\x12\x1f\n" +
	"\x04post\x18\x01 \x01(\v2\v.forum.PostR\x04post\"g\n" +
	"\x12CreatePostResponse\x120\n" +
	"\tbase_resp\x18\x01 \x01(\v2\x13.forum.BaseResponseR\bbaseResp\x12\x1f\n" +
	"\x04post\x18\x02 \x01(\v2\v.forum.PostR\x04post\"4\n" +
	"\x11UpdatePostRequest\x12\x1f\n" +
	"\x04post\x18\x01 \x01(\v2\v.forum.PostR\x04post\"F\n" +
	"\x12UpdatePostResponse\x120\n" +
	"\tbase_resp\x18\x01 \x01(\v2\x13.forum.BaseResponseR\bbaseResp\" \n" +
	"\x0eGetPostRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"d\n" +
	"\x0fGetPostResponse\x120\n" +
	"\tbase_resp\x18\x01 \x01(\v2\x13.forum.BaseResponseR\bbaseResp\x12\x1f\n" +
	"\x04post\x18\x02 \x01(\v2\v.forum.PostR\x04post\"\xd8\x01\n" +
	"\n" +
	"PostFilter\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\x03R\x06postId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12%\n" +
	"\x06status\x18\x03 \x03(\x0e2\r.forum.StatusR\x06status\x12\x18\n" +
	"\aaccount\x18\x04 \x01(\tR\aaccount\x12,\n" +
	"\x12publish_time_start\x18\x05 \x01(\x03R\x10publishTimeStart\x12(\n" +
	"\x10publish_time_end\x18\x06 \x01(\x03R\x0epublishTimeEnd\"\xf2\x01\n" +
	"\x0fListPostRequest\x121\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x11.forum.PaginationR\n" +
	"pagination\x122\n" +
	"\vpost_filter\x18\x02 \x01(\v2\x11.forum.PostFilterR\n" +
	"postFilter\x12!\n" +
	"\x05sorts\x18\x03 \x03(\v2\v.forum.SortR\x05sorts\x12\x1f\n" +
	"\voperator_id\x18\x04 \x01(\x03R\n" +
	"operatorId\x12\x17\n" +
	"\auser_id\x18\x05 \x01(\x03R\x06userId\x12\x1b\n" +
	"\tparent_id\x18\x06 \x01(\x03R\bparentId\"\x9a\x01\n" +
	"\x10ListPostResponse\x120\n" +
	"\tbase_resp\x18\x01 \x01(\v2\x13.forum.BaseResponseR\bbaseResp\x121\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x11.forum.PaginationR\n" +
	"pagination\x12!\n" +
	"\x05posts\x18\x03 \x03(\v2\v.forum.PostR\x05posts\"B\n" +
	"\n" +
	"FavRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1b\n" +
	"\ttarget_id\x18\x02 \x01(\x03R\btargetId\"?\n" +
	"\vFavResponse\x120\n" +
	"\tbase_resp\x18\x01 \x01(\v2\x13.forum.BaseResponseR\bbaseResp\"\x9e\x01\n" +
	"\x0eListFavRequest\x121\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x11.forum.PaginationR\n" +
	"pagination\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12!\n" +
	"\x05sorts\x18\x03 \x03(\v2\v.forum.SortR\x05sorts\x12\x1d\n" +
	"\n" +
	"target_ids\x18\x04 \x03(\x03R\ttargetIds\"\x96\x01\n" +
	"\x0fListFavResponse\x120\n" +
	"\tbase_resp\x18\x01 \x01(\v2\x13.forum.BaseResponseR\bbaseResp\x121\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x11.forum.PaginationR\n" +
	"pagination\x12\x1e\n" +
	"\x04favs\x18\x03 \x03(\v2\n" +
	".forum.FavR\x04favs\"z\n" +
	"\vLikeRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1b\n" +
	"\ttarget_id\x18\x02 \x01(\x03R\btargetId\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x03 \x01(\tR\tipAddress\x12\x16\n" +
	"\x06device\x18\x04 \x01(\x05R\x06device\"@\n" +
	"\fLikeResponse\x120\n" +
	"\tbase_resp\x18\x01 \x01(\v2\x13.forum.BaseResponseR\bbaseResp\"\x9f\x01\n" +
	"\x0fListLikeRequest\x121\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x11.forum.PaginationR\n" +
	"pagination\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12!\n" +
	"\x05sorts\x18\x03 \x03(\v2\v.forum.SortR\x05sorts\x12\x1d\n" +
	"\n" +
	"target_ids\x18\x04 \x03(\x03R\ttargetIds\"\x9a\x01\n" +
	"\x10ListLikeResponse\x120\n" +
	"\tbase_resp\x18\x01 \x01(\v2\x13.forum.BaseResponseR\bbaseResp\x121\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x11.forum.PaginationR\n" +
	"pagination\x12!\n" +
	"\x05likes\x18\x03 \x03(\v2\v.forum.LikeR\x05likes*F\n" +
	"\x06Status\x12\x12\n" +
	"\x0eSTATUS_UNKNOWN\x10\x00\x12\x14\n" +
	"\x10STATUS_PUBLISHED\x10\x1e\x12\x12\n" +
	"\x0eSTATUS_DELETED\x10Z2\xda\x03\n" +
	"\x05Forum\x12A\n" +
	"\n" +
	"CreatePost\x12\x18.forum.CreatePostRequest\x1a\x19.forum.CreatePostResponse\x12A\n" +
	"\n" +
	"UpdatePost\x12\x18.forum.UpdatePostRequest\x1a\x19.forum.UpdatePostResponse\x128\n" +
	"\aGetPost\x12\x15.forum.GetPostRequest\x1a\x16.forum.GetPostResponse\x12;\n" +
	"\bListPost\x12\x16.forum.ListPostRequest\x1a\x17.forum.ListPostResponse\x12,\n" +
	"\x03Fav\x12\x11.forum.FavRequest\x1a\x12.forum.FavResponse\x128\n" +
	"\aListFav\x12\x15.forum.ListFavRequest\x1a\x16.forum.ListFavResponse\x12/\n" +
	"\x04Like\x12\x12.forum.LikeRequest\x1a\x13.forum.LikeResponse\x12;\n" +
	"\bListLike\x12\x16.forum.ListLikeRequest\x1a\x17.forum.ListLikeResponseB\tZ\a./forumb\x06proto3"

var (
	file_forum_proto_rawDescOnce sync.Once
	file_forum_proto_rawDescData []byte
)

func file_forum_proto_rawDescGZIP() []byte {
	file_forum_proto_rawDescOnce.Do(func() {
		file_forum_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_forum_proto_rawDesc), len(file_forum_proto_rawDesc)))
	})
	return file_forum_proto_rawDescData
}

var file_forum_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_forum_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_forum_proto_goTypes = []any{
	(Status)(0),                // 0: forum.Status
	(*BaseResponse)(nil),       // 1: forum.BaseResponse
	(*Pagination)(nil),         // 2: forum.Pagination
	(*Sort)(nil),               // 3: forum.Sort
	(*Post)(nil),               // 4: forum.Post
	(*Like)(nil),               // 5: forum.Like
	(*Fav)(nil),                // 6: forum.Fav
	(*CreatePostRequest)(nil),  // 7: forum.CreatePostRequest
	(*CreatePostResponse)(nil), // 8: forum.CreatePostResponse
	(*UpdatePostRequest)(nil),  // 9: forum.UpdatePostRequest
	(*UpdatePostResponse)(nil), // 10: forum.UpdatePostResponse
	(*GetPostRequest)(nil),     // 11: forum.GetPostRequest
	(*GetPostResponse)(nil),    // 12: forum.GetPostResponse
	(*PostFilter)(nil),         // 13: forum.PostFilter
	(*ListPostRequest)(nil),    // 14: forum.ListPostRequest
	(*ListPostResponse)(nil),   // 15: forum.ListPostResponse
	(*FavRequest)(nil),         // 16: forum.FavRequest
	(*FavResponse)(nil),        // 17: forum.FavResponse
	(*ListFavRequest)(nil),     // 18: forum.ListFavRequest
	(*ListFavResponse)(nil),    // 19: forum.ListFavResponse
	(*LikeRequest)(nil),        // 20: forum.LikeRequest
	(*LikeResponse)(nil),       // 21: forum.LikeResponse
	(*ListLikeRequest)(nil),    // 22: forum.ListLikeRequest
	(*ListLikeResponse)(nil),   // 23: forum.ListLikeResponse
}
var file_forum_proto_depIdxs = []int32{
	0,  // 0: forum.Post.status:type_name -> forum.Status
	4,  // 1: forum.Post.parent:type_name -> forum.Post
	0,  // 2: forum.Like.status:type_name -> forum.Status
	0,  // 3: forum.Fav.status:type_name -> forum.Status
	4,  // 4: forum.Fav.post:type_name -> forum.Post
	4,  // 5: forum.CreatePostRequest.post:type_name -> forum.Post
	1,  // 6: forum.CreatePostResponse.base_resp:type_name -> forum.BaseResponse
	4,  // 7: forum.CreatePostResponse.post:type_name -> forum.Post
	4,  // 8: forum.UpdatePostRequest.post:type_name -> forum.Post
	1,  // 9: forum.UpdatePostResponse.base_resp:type_name -> forum.BaseResponse
	1,  // 10: forum.GetPostResponse.base_resp:type_name -> forum.BaseResponse
	4,  // 11: forum.GetPostResponse.post:type_name -> forum.Post
	0,  // 12: forum.PostFilter.status:type_name -> forum.Status
	2,  // 13: forum.ListPostRequest.pagination:type_name -> forum.Pagination
	13, // 14: forum.ListPostRequest.post_filter:type_name -> forum.PostFilter
	3,  // 15: forum.ListPostRequest.sorts:type_name -> forum.Sort
	1,  // 16: forum.ListPostResponse.base_resp:type_name -> forum.BaseResponse
	2,  // 17: forum.ListPostResponse.pagination:type_name -> forum.Pagination
	4,  // 18: forum.ListPostResponse.posts:type_name -> forum.Post
	1,  // 19: forum.FavResponse.base_resp:type_name -> forum.BaseResponse
	2,  // 20: forum.ListFavRequest.pagination:type_name -> forum.Pagination
	3,  // 21: forum.ListFavRequest.sorts:type_name -> forum.Sort
	1,  // 22: forum.ListFavResponse.base_resp:type_name -> forum.BaseResponse
	2,  // 23: forum.ListFavResponse.pagination:type_name -> forum.Pagination
	6,  // 24: forum.ListFavResponse.favs:type_name -> forum.Fav
	1,  // 25: forum.LikeResponse.base_resp:type_name -> forum.BaseResponse
	2,  // 26: forum.ListLikeRequest.pagination:type_name -> forum.Pagination
	3,  // 27: forum.ListLikeRequest.sorts:type_name -> forum.Sort
	1,  // 28: forum.ListLikeResponse.base_resp:type_name -> forum.BaseResponse
	2,  // 29: forum.ListLikeResponse.pagination:type_name -> forum.Pagination
	5,  // 30: forum.ListLikeResponse.likes:type_name -> forum.Like
	7,  // 31: forum.Forum.CreatePost:input_type -> forum.CreatePostRequest
	9,  // 32: forum.Forum.UpdatePost:input_type -> forum.UpdatePostRequest
	11, // 33: forum.Forum.GetPost:input_type -> forum.GetPostRequest
	14, // 34: forum.Forum.ListPost:input_type -> forum.ListPostRequest
	16, // 35: forum.Forum.Fav:input_type -> forum.FavRequest
	18, // 36: forum.Forum.ListFav:input_type -> forum.ListFavRequest
	20, // 37: forum.Forum.Like:input_type -> forum.LikeRequest
	22, // 38: forum.Forum.ListLike:input_type -> forum.ListLikeRequest
	8,  // 39: forum.Forum.CreatePost:output_type -> forum.CreatePostResponse
	10, // 40: forum.Forum.UpdatePost:output_type -> forum.UpdatePostResponse
	12, // 41: forum.Forum.GetPost:output_type -> forum.GetPostResponse
	15, // 42: forum.Forum.ListPost:output_type -> forum.ListPostResponse
	17, // 43: forum.Forum.Fav:output_type -> forum.FavResponse
	19, // 44: forum.Forum.ListFav:output_type -> forum.ListFavResponse
	21, // 45: forum.Forum.Like:output_type -> forum.LikeResponse
	23, // 46: forum.Forum.ListLike:output_type -> forum.ListLikeResponse
	39, // [39:47] is the sub-list for method output_type
	31, // [31:39] is the sub-list for method input_type
	31, // [31:31] is the sub-list for extension type_name
	31, // [31:31] is the sub-list for extension extendee
	0,  // [0:31] is the sub-list for field type_name
}

func init() { file_forum_proto_init() }
func file_forum_proto_init() {
	if File_forum_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_forum_proto_rawDesc), len(file_forum_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_forum_proto_goTypes,
		DependencyIndexes: file_forum_proto_depIdxs,
		EnumInfos:         file_forum_proto_enumTypes,
		MessageInfos:      file_forum_proto_msgTypes,
	}.Build()
	File_forum_proto = out.File
	file_forum_proto_goTypes = nil
	file_forum_proto_depIdxs = nil
}
